/**
 * KanoTab — Kano Classification. Data-driven from generic {sections, tables} JSON.
 * Kano data is not generated by the new_markets workflow, so this shows a placeholder.
 */
import { getMarket } from "@/data";

export default function KanoTab({ marketSlug }: { marketSlug: string }) {
  let kanoData: any = null;
  try { kanoData = getMarket(marketSlug).kano; } catch { /* */ }

  const features = kanoData?.features ?? [];
  const marketName = kanoData?.marketName ?? marketSlug;

  if (features.length === 0) {
    return (
      <div className="section">
        <div className="section__eyebrow">Kano Classification · {marketName}</div>
        <h2 className="section__title">Kano Classification</h2>
        <p className="section__sub">
          Kano feature classification data for this market has not been generated yet.
          The new_markets workflow does not include a Kano analysis step — this tab will
          be populated when the FIT pipeline adds Kano classification.
        </p>
      </div>
    );
  }

  // If we have features, render them (for future use)
  return (
    <div className="section">
      <div className="section__eyebrow">Kano Classification · {marketName}</div>
      <h2 className="section__title">Kano Classification</h2>
      <p className="section__sub">{features.length} features classified.</p>
    </div>
  );
}
