/**
 * Data layer for the Mein Solar GmbH — Großbatteriespeicher report app.
 *
 * All JSON files in this directory are generated by the Clayton orchestrator
 * and transform_data.py. Import from here — never import JSON files directly
 * in UI code.
 *
 * Usage:
 *   import { product, ranking, markets } from "@/data";
 *   import { getMarket, getODI, listMarkets } from "@/data";
 */

import type {
  ProductDecomposition,
  FunctionalPromiseData,
  ConstraintsData,
  HomeMarketCompetition,
  MarketDiscovery,
  RankingData,
  SourcesRegistry,
  MarketIndexEntry,
  JTBDData,
  ODIData,
  ValueNetworkData,
  KanoData,
  CompatibilityData,
  AlternativesData,
  MarketMeta,
  BOMData,
} from "@/types";

// ─── Static JSON imports ──────────────────────────────────────────────────────

import _product from "./product.json";
import _functionalPromise from "./functionalPromise.json";
import _constraints from "./constraints.json";
import _homeMarket from "./homeMarketCompetition.json";
import _marketDiscovery from "./marketDiscovery.json";
import _ranking from "./ranking.json";
import _sources from "./sources.json";
import _marketsIndex from "./markets/index.json";

// ─── Market data imports — one per slug ───────────────────────────────────────

// bess_power_generation
import _bessMeta from "./markets/bess_power_generation/meta.json";
import _bessJtbd from "./markets/bess_power_generation/jtbd.json";
import _bessOdi from "./markets/bess_power_generation/odi.json";
import _bessVn from "./markets/bess_power_generation/valueNetwork.json";
import _bessKano from "./markets/bess_power_generation/kano.json";
import _bessCompat from "./markets/bess_power_generation/compatibility.json";
import _bessAlt from "./markets/bess_power_generation/alternatives.json";
import _bessBom from "./markets/bess_power_generation/bom.json";

// solar_power_generation
import _solarMeta from "./markets/solar_power_generation/meta.json";
import _solarJtbd from "./markets/solar_power_generation/jtbd.json";
import _solarOdi from "./markets/solar_power_generation/odi.json";
import _solarVn from "./markets/solar_power_generation/valueNetwork.json";
import _solarKano from "./markets/solar_power_generation/kano.json";
import _solarCompat from "./markets/solar_power_generation/compatibility.json";
import _solarAlt from "./markets/solar_power_generation/alternatives.json";
import _solarBom from "./markets/solar_power_generation/bom.json";

// wind_power_generation
import _windMeta from "./markets/wind_power_generation/meta.json";
import _windJtbd from "./markets/wind_power_generation/jtbd.json";
import _windOdi from "./markets/wind_power_generation/odi.json";
import _windVn from "./markets/wind_power_generation/valueNetwork.json";
import _windKano from "./markets/wind_power_generation/kano.json";
import _windCompat from "./markets/wind_power_generation/compatibility.json";
import _windAlt from "./markets/wind_power_generation/alternatives.json";
import _windBom from "./markets/wind_power_generation/bom.json";

// electric_power_distribution
import _distribMeta from "./markets/electric_power_distribution/meta.json";
import _distribJtbd from "./markets/electric_power_distribution/jtbd.json";
import _distribOdi from "./markets/electric_power_distribution/odi.json";
import _distribVn from "./markets/electric_power_distribution/valueNetwork.json";
import _distribKano from "./markets/electric_power_distribution/kano.json";
import _distribCompat from "./markets/electric_power_distribution/compatibility.json";
import _distribAlt from "./markets/electric_power_distribution/alternatives.json";
import _distribBom from "./markets/electric_power_distribution/bom.json";

// port_harbor_operations
import _portMeta from "./markets/port_harbor_operations/meta.json";
import _portJtbd from "./markets/port_harbor_operations/jtbd.json";
import _portOdi from "./markets/port_harbor_operations/odi.json";
import _portVn from "./markets/port_harbor_operations/valueNetwork.json";
import _portKano from "./markets/port_harbor_operations/kano.json";
import _portCompat from "./markets/port_harbor_operations/compatibility.json";
import _portAlt from "./markets/port_harbor_operations/alternatives.json";
import _portBom from "./markets/port_harbor_operations/bom.json";

// semiconductor_manufacturing
import _semiMeta from "./markets/semiconductor_manufacturing/meta.json";
import _semiJtbd from "./markets/semiconductor_manufacturing/jtbd.json";
import _semiOdi from "./markets/semiconductor_manufacturing/odi.json";
import _semiVn from "./markets/semiconductor_manufacturing/valueNetwork.json";
import _semiKano from "./markets/semiconductor_manufacturing/kano.json";
import _semiCompat from "./markets/semiconductor_manufacturing/compatibility.json";
import _semiAlt from "./markets/semiconductor_manufacturing/alternatives.json";
import _semiBom from "./markets/semiconductor_manufacturing/bom.json";

// refrigerated_warehousing
import _refrMeta from "./markets/refrigerated_warehousing/meta.json";
import _refrJtbd from "./markets/refrigerated_warehousing/jtbd.json";
import _refrOdi from "./markets/refrigerated_warehousing/odi.json";
import _refrVn from "./markets/refrigerated_warehousing/valueNetwork.json";
import _refrKano from "./markets/refrigerated_warehousing/kano.json";
import _refrCompat from "./markets/refrigerated_warehousing/compatibility.json";
import _refrAlt from "./markets/refrigerated_warehousing/alternatives.json";
import _refrBom from "./markets/refrigerated_warehousing/bom.json";

// nonresidential_buildings
import _nresMeta from "./markets/nonresidential_buildings/meta.json";
import _nresJtbd from "./markets/nonresidential_buildings/jtbd.json";
import _nresOdi from "./markets/nonresidential_buildings/odi.json";
import _nresVn from "./markets/nonresidential_buildings/valueNetwork.json";
import _nresKano from "./markets/nonresidential_buildings/kano.json";
import _nresCompat from "./markets/nonresidential_buildings/compatibility.json";
import _nresAlt from "./markets/nonresidential_buildings/alternatives.json";
import _nresBom from "./markets/nonresidential_buildings/bom.json";

// ─── Typed exports ────────────────────────────────────────────────────────────

export const product = _product as unknown as ProductDecomposition;
export const functionalPromise = _functionalPromise as unknown as FunctionalPromiseData;
export const constraints = _constraints as unknown as ConstraintsData;
export const homeMarket = _homeMarket as unknown as HomeMarketCompetition;
export const marketDiscovery = _marketDiscovery as unknown as MarketDiscovery;
export const ranking = _ranking as unknown as RankingData;
export const sources = _sources as unknown as SourcesRegistry;
export const marketsIndex = _marketsIndex as unknown as MarketIndexEntry[];

// ─── Kano normalizer ────────────────────────────────────────────────────────
function normalizeKano(raw: any): KanoData {
  if (!raw?.features) return raw as KanoData;
  return {
    ...raw,
    features: raw.features.map((f: any) => ({
      featureName: f.featureName ?? f.name ?? "",
      kanoClassification: f.kanoClassification ?? f.kanoClass ?? "indifferent",
      scores: {
        ...(f.scores ?? {}),
        overall: f.scores?.overall ?? f.overallFit ?? 0,
      },
      rationale: f.rationale ?? "",
    })),
  } as KanoData;
}

// ─── Per-market data bundles ──────────────────────────────────────────────────

export interface MarketBundle {
  meta: MarketMeta;
  jtbd: JTBDData;
  odi: ODIData;
  valueNetwork: ValueNetworkData;
  kano: KanoData;
  compatibility: CompatibilityData;
  alternatives: AlternativesData;
  bom: BOMData;
}

const _marketBundles: Record<string, MarketBundle> = {
  "bess_power_generation": {
    meta: _bessMeta as unknown as MarketMeta,
    jtbd: _bessJtbd as unknown as JTBDData,
    odi: _bessOdi as unknown as ODIData,
    valueNetwork: _bessVn as unknown as ValueNetworkData,
    kano: normalizeKano(_bessKano),
    compatibility: _bessCompat as unknown as CompatibilityData,
    alternatives: _bessAlt as unknown as AlternativesData,
    bom: _bessBom as unknown as BOMData,
  },
  "solar_power_generation": {
    meta: _solarMeta as unknown as MarketMeta,
    jtbd: _solarJtbd as unknown as JTBDData,
    odi: _solarOdi as unknown as ODIData,
    valueNetwork: _solarVn as unknown as ValueNetworkData,
    kano: normalizeKano(_solarKano),
    compatibility: _solarCompat as unknown as CompatibilityData,
    alternatives: _solarAlt as unknown as AlternativesData,
    bom: _solarBom as unknown as BOMData,
  },
  "wind_power_generation": {
    meta: _windMeta as unknown as MarketMeta,
    jtbd: _windJtbd as unknown as JTBDData,
    odi: _windOdi as unknown as ODIData,
    valueNetwork: _windVn as unknown as ValueNetworkData,
    kano: normalizeKano(_windKano),
    compatibility: _windCompat as unknown as CompatibilityData,
    alternatives: _windAlt as unknown as AlternativesData,
    bom: _windBom as unknown as BOMData,
  },
  "electric_power_distribution": {
    meta: _distribMeta as unknown as MarketMeta,
    jtbd: _distribJtbd as unknown as JTBDData,
    odi: _distribOdi as unknown as ODIData,
    valueNetwork: _distribVn as unknown as ValueNetworkData,
    kano: normalizeKano(_distribKano),
    compatibility: _distribCompat as unknown as CompatibilityData,
    alternatives: _distribAlt as unknown as AlternativesData,
    bom: _distribBom as unknown as BOMData,
  },
  "port_harbor_operations": {
    meta: _portMeta as unknown as MarketMeta,
    jtbd: _portJtbd as unknown as JTBDData,
    odi: _portOdi as unknown as ODIData,
    valueNetwork: _portVn as unknown as ValueNetworkData,
    kano: normalizeKano(_portKano),
    compatibility: _portCompat as unknown as CompatibilityData,
    alternatives: _portAlt as unknown as AlternativesData,
    bom: _portBom as unknown as BOMData,
  },
  "semiconductor_manufacturing": {
    meta: _semiMeta as unknown as MarketMeta,
    jtbd: _semiJtbd as unknown as JTBDData,
    odi: _semiOdi as unknown as ODIData,
    valueNetwork: _semiVn as unknown as ValueNetworkData,
    kano: normalizeKano(_semiKano),
    compatibility: _semiCompat as unknown as CompatibilityData,
    alternatives: _semiAlt as unknown as AlternativesData,
    bom: _semiBom as unknown as BOMData,
  },
  "refrigerated_warehousing": {
    meta: _refrMeta as unknown as MarketMeta,
    jtbd: _refrJtbd as unknown as JTBDData,
    odi: _refrOdi as unknown as ODIData,
    valueNetwork: _refrVn as unknown as ValueNetworkData,
    kano: normalizeKano(_refrKano),
    compatibility: _refrCompat as unknown as CompatibilityData,
    alternatives: _refrAlt as unknown as AlternativesData,
    bom: _refrBom as unknown as BOMData,
  },
  "nonresidential_buildings": {
    meta: _nresMeta as unknown as MarketMeta,
    jtbd: _nresJtbd as unknown as JTBDData,
    odi: _nresOdi as unknown as ODIData,
    valueNetwork: _nresVn as unknown as ValueNetworkData,
    kano: normalizeKano(_nresKano),
    compatibility: _nresCompat as unknown as CompatibilityData,
    alternatives: _nresAlt as unknown as AlternativesData,
    bom: _nresBom as unknown as BOMData,
  },
};

export const markets = _marketBundles;

// ─── Helper functions ─────────────────────────────────────────────────────────

export function getMarket(slug: string): MarketBundle {
  const bundle = _marketBundles[slug];
  if (!bundle) {
    throw new Error(
      `Unknown market slug: "${slug}". Available: ${Object.keys(_marketBundles).join(", ")}`
    );
  }
  return bundle;
}

export function getODI(slug: string): ODIData {
  return getMarket(slug).odi;
}

export function getJTBD(slug: string): JTBDData {
  return getMarket(slug).jtbd;
}

export function getKano(slug: string): KanoData {
  return getMarket(slug).kano;
}

export function getValueNetwork(slug: string): ValueNetworkData {
  return getMarket(slug).valueNetwork;
}

export function getCompatibility(slug: string): CompatibilityData {
  return getMarket(slug).compatibility;
}

export function listMarkets(): MarketIndexEntry[] {
  return marketsIndex;
}

export function listNewMarkets(): MarketIndexEntry[] {
  return marketsIndex.filter((m) => !m.isReference);
}

export function getMarketMeta(slug: string): MarketMeta {
  return getMarket(slug).meta;
}

export function getRankedMarkets() {
  return [...((ranking as any).rankedMarkets || [])].sort(
    (a: any, b: any) => (b.scores?.composite ?? 0) - (a.scores?.composite ?? 0)
  );
}

export function getSource(prefixedId: string): import("@/types").Source | undefined {
  return (sources as SourcesRegistry)[prefixedId];
}

export function getBOM(slug: string): BOMData {
  return getMarket(slug).bom;
}
