/**
 * Data layer for the Mein Solar GmbH — Grossbatteriespeicher report app.
 *
 * All JSON files in this directory are generated by the Clayton orchestrator
 * and transform_data.py. Import from here — never import JSON files directly
 * in UI code.
 *
 * Market data is auto-discovered via Vite's import.meta.glob — adding or
 * removing a market folder under ./markets/ requires zero code changes.
 *
 * Usage:
 *   import { product, ranking, markets } from "@/data";
 *   import { getMarket, getODI, listMarkets } from "@/data";
 */

import type {
  ProductDecomposition,
  FunctionalPromiseData,
  ConstraintsData,
  HomeMarketCompetition,
  MarketDiscovery,
  RankingData,
  SourcesRegistry,
  MarketIndexEntry,
  JTBDData,
  ODIData,
  ValueNetworkData,
  KanoData,
  CompatibilityData,
  AlternativesData,
  MarketMeta,
  BOMData,
} from "@/types";

// ─── Static JSON imports ──────────────────────────────────────────────────────

import _product from "./product.json";
import _functionalPromise from "./functionalPromise.json";
import _constraints from "./constraints.json";
import _homeMarket from "./homeMarketCompetition.json";
import _marketDiscovery from "./marketDiscovery.json";
import _ranking from "./ranking.json";
import _sources from "./sources.json";
import _marketsIndex from "./markets/index.json";

// ─── Typed exports ────────────────────────────────────────────────────────────

export const product = _product as unknown as ProductDecomposition;
export const functionalPromise = _functionalPromise as unknown as FunctionalPromiseData;
export const constraints = _constraints as unknown as ConstraintsData;
export const homeMarket = _homeMarket as unknown as HomeMarketCompetition;
export const marketDiscovery = _marketDiscovery as unknown as MarketDiscovery;
export const ranking = _ranking as unknown as RankingData;
export const sources = _sources as unknown as SourcesRegistry;
export const marketsIndex = _marketsIndex as unknown as MarketIndexEntry[];

// ─── Kano normalizer ────────────────────────────────────────────────────────
function normalizeKano(raw: any): KanoData {
  if (!raw?.features) return raw as KanoData;
  return {
    ...raw,
    features: raw.features.map((f: any) => ({
      featureName: f.featureName ?? f.name ?? "",
      kanoClassification: f.kanoClassification ?? f.kanoClass ?? "indifferent",
      scores: {
        ...(f.scores ?? {}),
        overall: f.scores?.overall ?? f.overallFit ?? 0,
      },
      rationale: f.rationale ?? "",
    })),
  } as KanoData;
}

// ─── Dynamic per-market data loading via import.meta.glob ────────────────────

export interface MarketBundle {
  meta: MarketMeta;
  jtbd: JTBDData;
  odi: ODIData;
  valueNetwork: ValueNetworkData;
  kano: KanoData;
  compatibility: CompatibilityData;
  alternatives: AlternativesData;
  bom: BOMData;
}

/**
 * Vite's import.meta.glob eagerly loads every meta.json + sibling files.
 * Pattern: ./markets/<slug>/<file>.json
 * Keyed by path like "./markets/bess_power_generation/meta.json"
 */
const allMarketFiles = import.meta.glob<{ default: unknown }>(
  "./markets/*/meta.json",
  { eager: true }
);

const jtbdFiles = import.meta.glob<{ default: unknown }>(
  "./markets/*/jtbd.json",
  { eager: true }
);

const odiFiles = import.meta.glob<{ default: unknown }>(
  "./markets/*/odi.json",
  { eager: true }
);

const vnFiles = import.meta.glob<{ default: unknown }>(
  "./markets/*/valueNetwork.json",
  { eager: true }
);

const kanoFiles = import.meta.glob<{ default: unknown }>(
  "./markets/*/kano.json",
  { eager: true }
);

const compatFiles = import.meta.glob<{ default: unknown }>(
  "./markets/*/compatibility.json",
  { eager: true }
);

const altFiles = import.meta.glob<{ default: unknown }>(
  "./markets/*/alternatives.json",
  { eager: true }
);

const bomFiles = import.meta.glob<{ default: unknown }>(
  "./markets/*/bom.json",
  { eager: true }
);

/** Extract the slug from a glob path like "./markets/bess_power_generation/meta.json" */
function slugFromPath(path: string): string {
  const parts = path.split("/");
  // parts = [".", "markets", "<slug>", "file.json"]
  return parts[2];
}

/** Lookup a file from a glob result by slug */
function lookup(files: Record<string, { default: unknown }>, slug: string, fileName: string): unknown {
  const key = `./markets/${slug}/${fileName}`;
  return files[key]?.default ?? null;
}

/** Build all market bundles dynamically */
function buildMarketBundles(): Record<string, MarketBundle> {
  const bundles: Record<string, MarketBundle> = {};

  for (const path of Object.keys(allMarketFiles)) {
    const slug = slugFromPath(path);
    const meta = allMarketFiles[path]?.default;
    if (!meta) continue;

    const jtbd = lookup(jtbdFiles, slug, "jtbd.json");
    const odi = lookup(odiFiles, slug, "odi.json");
    const vn = lookup(vnFiles, slug, "valueNetwork.json");
    const kanoRaw = lookup(kanoFiles, slug, "kano.json");
    const compat = lookup(compatFiles, slug, "compatibility.json");
    const alt = lookup(altFiles, slug, "alternatives.json");
    const bom = lookup(bomFiles, slug, "bom.json");

    bundles[slug] = {
      meta: meta as unknown as MarketMeta,
      jtbd: jtbd as unknown as JTBDData,
      odi: odi as unknown as ODIData,
      valueNetwork: vn as unknown as ValueNetworkData,
      kano: normalizeKano(kanoRaw),
      compatibility: compat as unknown as CompatibilityData,
      alternatives: alt as unknown as AlternativesData,
      bom: bom as unknown as BOMData,
    };
  }

  return bundles;
}

const _marketBundles = buildMarketBundles();

export const markets = _marketBundles;

// ─── Helper functions ─────────────────────────────────────────────────────────

export function getMarket(slug: string): MarketBundle {
  const bundle = _marketBundles[slug];
  if (!bundle) {
    throw new Error(
      `Unknown market slug: "${slug}". Available: ${Object.keys(_marketBundles).join(", ")}`
    );
  }
  return bundle;
}

export function getODI(slug: string): ODIData {
  return getMarket(slug).odi;
}

export function getJTBD(slug: string): JTBDData {
  return getMarket(slug).jtbd;
}

export function getKano(slug: string): KanoData {
  return getMarket(slug).kano;
}

export function getValueNetwork(slug: string): ValueNetworkData {
  return getMarket(slug).valueNetwork;
}

export function getCompatibility(slug: string): CompatibilityData {
  return getMarket(slug).compatibility;
}

export function listMarkets(): MarketIndexEntry[] {
  return marketsIndex;
}

export function listNewMarkets(): MarketIndexEntry[] {
  return marketsIndex.filter((m) => !m.isReference);
}

export function getMarketMeta(slug: string): MarketMeta {
  return getMarket(slug).meta;
}

export function getRankedMarkets() {
  return [...((ranking as any).rankedMarkets || [])].sort(
    (a: any, b: any) => (b.scores?.composite ?? 0) - (a.scores?.composite ?? 0)
  );
}

export function getSource(prefixedId: string): import("@/types").Source | undefined {
  return (sources as SourcesRegistry)[prefixedId];
}

export function getBOM(slug: string): BOMData {
  return getMarket(slug).bom;
}
